/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.math.BigDecimal;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getPaymentMessage(), "app should have a payment message");
    }

    @Test void appCanPrintTransaction() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.formatTransaction(new BigDecimal("5000"), new BigDecimal("0.02"), "Checkout.com", "GBP"), "app should be able to print a transaction");
    }
}
