/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getPaymentMessage(), "app should have a payment message");
    }

    @Test void appCanPrintTransaction() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.printTransaction(), "app should be able to print a transaction");
    }
}
