/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public String getPaymentMessage() {
        return "Payment Calculator v1.0\nReady to process transactions ";
    }

    public static void main(String[] args) {
        System.out.println(new App().getPaymentMessage());
    }
}
